config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :courses
  resources :subjects

  root "student_dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    def initialize(user)
      user ||= User.new
      if user.role?(:lecturer)
        can :manage, :all
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
 class Course < ApplicationRecord

	has_many :subjects
	has_many :lecturers, through: :subjects
end

app/models/lecturer.rb
class Lecturer < User

	has_many :subjects
	has_many :courses, through: :subjects
end

app/models/notification.rb
class Notification < ApplicationRecord

	belongs_to :user
end

app/models/student.rb
class Student < User

	has_many :subjects
	has_many :lecturers, through: :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord

  belongs_to :course
  has_many :uploads
  has_many :lecturers

  enum student_class: [:computing, :networking, :multimedia, :bba]

end

app/models/upload.rb
class Upload < ApplicationRecord

	has_many :subjects
	has_many :users, through: :subjects

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course, notice: "#{@course.title} has been created" and return
    end
    render "new"
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      redirect_to @course, notice: "#{@course.title} has been updated!" and return
    end
    render "edit"
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.destroy
      redirect_to courses_path, notice: "#{@course.title} has deleted successfully"
    end
  end

  private

  def course_params
    params.require(:course).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def update
  	id = params[:id].to_i
    session[:id] = User::ROLES.has_key?(id) ? id : 0
    flash[:success] = "Your new role #{User::ROLES[id]} was set!"
    redirect_to root_path
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @course = Course.find(params[:course_id])
    @subjects = @course.subjects
  end

  def new
    @course = Course.find(params[:course_id])
    @subject = @course.subjects.new
  end

  def create
    @course = Course.find(params[:course_id])
    @subject = @course.subjects.new(subject_params)

    if @subject.save
      redirect_to [@subject.course, @subject], notice: "The subject has been created!" and return
    end
    render 'new'
  end

  def edit
    @course = Course.find(params[:course_id])
    @subject = @course.subjects.find(params[:id])
  end

  def update
    @course = Course.find(params[:course_id])
    @subject = @course.subjects.find(params[:id])
    if @subject.update_attributes(subject_params)
      redirect_to [@subject.course, @subjects], notice: "#{title} has been updated!" and return
    end

    render 'edit'
  end

  def destroy
    @course = Course.find(params[:course_id])
    @subject = @course.subjects.find(params[:id])
    if @subject.destroy

    redirect_to course_subjects_url, notice: "#{title} has been deleted!" and return
  end
private
  def subject_params
    params.require(:subject).permit(:title)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.create
      redirect_to root_url, notice: "A new user has created"
    else
      redirect_to new_user_registration_path
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_url, notice: "A user is updated"
    else
      redirect_to edit_user_registration_path
    end
  end

  def destroy
    @user.destroy
    redirect_to user_session_path, notice: "The user has successfully destroyed"
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :address,
                                 :phone_name,
                                 :email,
                                 :password,
                                 :passwor_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_dashboard_helper.rb
module StudentDashboardHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subjects/_form.html.erb
<h3> Form to add subject </h3>

<%= form_for :subject, url: { :action => 'create' } do |f| %>
	<%= f.label :Title%>
	<div>
		<%= f.text_field :title, placeholder: 'Enter Subject Title'%>
	</div>

	<div>
		<%= f.submit 'Submit'%>
	</div>

<%end%>

app/views/subjects/create.html.erb
<h1>Subjects#create</h1>
<p>Find me in app/views/subjects/create.html.erb</p>

app/views/subjects/destroy.html.erb
<h1>Subjects#destroy</h1>
<p>Find me in app/views/subjects/destroy.html.erb</p>

app/views/subjects/edit.html.erb
<div class="well">
	<%= render 'form'%>
	<%= link_to 'Show', [@subject.course, @subject] %> |
	<%= link_to 'Back', course_subjects_path(@subject.course) %>
</div>

app/views/subjects/index.html.erb
<h1>Subjects</h1>
<div class="well">
  <%= link_to "New Subject", new_subject_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Subject Title</th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.title %></td>
        <td>
          <%= link_to "Edit", edit_subject_path(subject), class: "btn btn-default" %>
        </td>
        <td>
          <%= button_to "Delete", subject, method: :delete, data: { confirm: "Are you sure you wish to delete" "#{subject.title}" }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subjects/new.html.erb
<div class="well">
	<%= render 'form'%>
	<%= link_to 'Back', course_subjects_path(@subject.course)%>
</div>

app/views/subjects/show.html.erb
<div class="well">
  <h4> Recently added subject</h4>
  <div>
    <%= @subject.title%>
  </div>
  <%= link_to 'Edit', edit_course_subject_path(@subject.course, @subject) %> |
  <%= link_to 'Back', course_subjects_path(@subject.course) %>
</div>

app/views/subjects/update.html.erb
<h1>Subjects#update</h1>
<p>Find me in app/views/subjects/update.html.erb</p>

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/uploads/destroy.html.erb
<h1>Uploads#destroy</h1>
<p>Find me in app/views/uploads/destroy.html.erb</p>

app/views/uploads/edit.html.erb
<h1>Uploads#edit</h1>
<p>Find me in app/views/uploads/edit.html.erb</p>

app/views/uploads/index.html.erb
<h1>Uploads#index</h1>
<p>Find me in app/views/uploads/index.html.erb</p>

app/views/uploads/new.html.erb
<h1>Uploads#new</h1>
<p>Find me in app/views/uploads/new.html.erb</p>

app/views/uploads/show.html.erb
<h1>Uploads#show</h1>
<p>Find me in app/views/uploads/show.html.erb</p>

app/views/uploads/update.html.erb
<h1>Uploads#update</h1>
<p>Find me in app/views/uploads/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>